import Link from "next/link";
import Header from "@/components/Header";

const checklist = [
  { label: "10+ posts with this pain", passed: true },
  { label: "Paying for inferior solution", passed: true },
  { label: "Reachable channel", passed: true },
  { label: "MVP < 4 weeks", passed: true },
  { label: "Price point high enough", passed: true },
  { label: "Hair-on-fire problem", passed: false },
  { label: "Can pre-sell", passed: true },
  { label: "< 3 competitors", passed: true },
  { label: "AI-agent operable", passed: true },
];

const painPoints = [
  {
    problem:
      "Real estate investors struggle to track finances across multiple properties, understand true value per property, and identify which are generating cash flow vs. costing money.",
    persona: "Real estate investor managing multiple properties",
    workaround: "Juggling multiple spreadsheets to track properties and finances",
    frequency: "weekly",
    wtp: "Built custom dashboard (Earn Clarity) to replace spreadsheets",
    source:
      "https://www.reddit.com/r/SideProject/comments/1unp3zy/got_tired_of_juggling_spreadsheets_to_track_my/",
  },
  {
    problem:
      "Managing multiple spreadsheets for rental properties is tedious and doesn't provide unified visibility into tenants, maintenance, rent tracking, and financial performance.",
    persona: "Landlord managing multiple rental properties",
    workaround:
      "Managing multiple spreadsheets or ditching property management apps entirely",
    frequency: "weekly",
    wtp: "Built custom Notion system to consolidate property management",
    source:
      "https://www.reddit.com/r/Notion/comments/1ue3u6b/built_a_notion_system_to_manage_my_rental/",
  },
];

export default function ResearchPage() {
  return (
    <>
      <Header active="research" />
      <div className="mx-auto max-w-4xl px-6 py-12">
        <div className="mb-12">
          <p className="text-sm font-medium uppercase tracking-wider text-brand-400">
            Idea Miner Research
          </p>
          <h1 className="mt-2 font-display text-3xl font-bold text-white sm:text-4xl">
            How we found PropertyNarrator
          </h1>
          <p className="mt-4 text-lg text-slate-400">
            AI turns raw property numbers into plain-English investment verdicts
            landlords actually understand.
          </p>
        </div>

        {/* Score badge */}
        <div className="mb-12 flex flex-wrap gap-4">
          <div className="glass-card px-6 py-4 text-center">
            <p className="text-3xl font-bold text-brand-400">108/130</p>
            <p className="text-xs text-slate-500">Weighted rubric score</p>
          </div>
          <div className="glass-card px-6 py-4 text-center">
            <p className="text-3xl font-bold text-white">8/9</p>
            <p className="text-xs text-slate-500">Validation checks passed</p>
          </div>
          <div className="glass-card px-6 py-4 text-center">
            <p className="text-sm font-semibold text-white">Rental Property</p>
            <p className="text-xs text-slate-500">Financial Tracking cluster</p>
          </div>
        </div>

        {/* Why research exists */}
        <section className="mb-12">
          <h2 className="mb-4 font-display text-2xl font-semibold text-white">
            Why this research program exists
          </h2>
          <p className="leading-relaxed text-slate-400">
            This app was auto-generated by the <strong className="text-slate-200">Idea Miner</strong> pipeline — a twice-daily research
            program that hunts for validated micro-SaaS opportunities from real people expressing
            real pain online (Reddit, Hacker News, Stack Exchange, GitHub, and more).
          </p>

          <h3 className="mb-3 mt-8 text-lg font-semibold text-white">
            What we&apos;re looking for
          </h3>
          <ul className="space-y-2 text-slate-400">
            <li className="flex gap-2">
              <span className="text-brand-400">•</span>
              <span><strong className="text-slate-300">Self-running micro-SaaS</strong> — one specific problem, a small dedicated user base, minimal manual ops (digital-nomad friendly).</span>
            </li>
            <li className="flex gap-2">
              <span className="text-brand-400">•</span>
              <span><strong className="text-slate-300">AI-agent operable</strong> — daily support, content, and processing handled by autonomous agents on self-hosted LLMs (not locked into expensive cloud API token bills).</span>
            </li>
            <li className="flex gap-2">
              <span className="text-brand-400">•</span>
              <span><strong className="text-slate-300">Real pain only</strong> — every idea must trace back to actual posts where people complain, ask &ldquo;is there a tool for X?&rdquo;, or say &ldquo;I wish someone would build…&rdquo;.</span>
            </li>
            <li className="flex gap-2">
              <span className="text-brand-400">•</span>
              <span><strong className="text-slate-300">B2B &amp; recurring revenue preferred</strong> — higher willingness to pay, lower churn.</span>
            </li>
            <li className="flex gap-2">
              <span className="text-brand-400">•</span>
              <span><strong className="text-slate-300">Markets with &lt;3 established competitors</strong> — room for a focused wedge.</span>
            </li>
            <li className="flex gap-2">
              <span className="text-brand-400">•</span>
              <span><strong className="text-slate-300">MVP in under 4 weeks</strong> — solo-dev buildable, no regulatory/hardware/capital barriers.</span>
            </li>
          </ul>
        </section>

        {/* Why demo built */}
        <section className="mb-12">
          <h2 className="mb-4 font-display text-2xl font-semibold text-white">
            Why this demo was built
          </h2>
          <p className="leading-relaxed text-slate-400">
            When an idea passes the validation gate (≥8/9 checklist items, not declining on Google
            Trends, not previously built), the pipeline automatically ships a working mock on
            Vercel so we can see the product story, not just a slide deck.
          </p>
        </section>

        {/* This specific idea */}
        <section className="mb-12">
          <h2 className="mb-4 font-display text-2xl font-semibold text-white">
            This specific idea
          </h2>
          <p className="mb-4 leading-relaxed text-slate-400">
            PropertyNarrator scored <strong className="text-brand-400">108/130</strong> on the weighted rubric and passed <strong className="text-brand-400">8/9</strong> validation checks.
          </p>
          <div className="glass-card p-6">
            <p className="text-sm text-slate-500">Cluster</p>
            <p className="font-semibold text-white">Rental Property Financial Tracking</p>
            <p className="mt-4 text-sm text-slate-500">Why we built this demo</p>
            <p className="text-slate-300">
              AI narrative output is differentiated — investors share the PDF memo with partners, creating viral word-of-mouth; self-hosted LLM makes per-report cost negligible
            </p>
          </div>
        </section>

        {/* Product spec */}
        <section className="mb-12">
          <h2 className="mb-4 font-display text-2xl font-semibold text-white">
            Product specification
          </h2>
          <p className="mb-4 text-slate-400">
            <strong className="text-slate-300">Target customer:</strong> Real estate investors evaluating new acquisitions or reviewing existing portfolio performance
          </p>

          <h3 className="mb-3 text-lg font-semibold text-white">Core MVP features</h3>
          <ul className="mb-6 space-y-2 text-slate-400">
            <li className="flex gap-2"><span className="text-brand-400">✓</span> Input property address + purchase price + rent + expenses; AI fetches comparable rents via public data</li>
            <li className="flex gap-2"><span className="text-brand-400">✓</span> Generates plain-English verdict: &lsquo;This property cash flows $340/mo but your cap rate is below market — here&apos;s why&apos;</li>
            <li className="flex gap-2"><span className="text-brand-400">✓</span> Side-by-side portfolio comparison: rank all properties by cash-on-cash return</li>
            <li className="flex gap-2"><span className="text-brand-400">✓</span> What-if scenario engine: &lsquo;What if rent increases 10%?&rsquo; or &lsquo;What if vacancy hits 15%?&rsquo;</li>
            <li className="flex gap-2"><span className="text-brand-400">✓</span> Shareable PDF deal memo for partners or lenders, auto-generated by AI</li>
          </ul>

          <div className="grid gap-4 sm:grid-cols-2">
            <div className="glass-card p-4">
              <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Pricing</p>
              <p className="mt-1 text-sm text-slate-300">$9 per deal report (pay-as-you-go) or $39/mo unlimited reports</p>
            </div>
            <div className="glass-card p-4">
              <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Go-to-market</p>
              <p className="mt-1 text-sm text-slate-300">BiggerPockets community, r/realestateinvesting, real estate investor Facebook groups, SEO targeting &lsquo;rental property cash flow calculator&rsquo;</p>
            </div>
            <div className="glass-card p-4">
              <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Competitive landscape</p>
              <p className="mt-1 text-sm text-slate-300">DealCheck exists for deal analysis but produces raw numbers with no narrative; no tool generates plain-English investment memos with AI narrative for small investors</p>
            </div>
            <div className="glass-card p-4">
              <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Agentic automation</p>
              <p className="mt-1 text-sm text-slate-300">User submits property data; agent auto-fetches public rent comps, runs financial model, generates narrative via LLM, renders PDF — fully automated from input to downloadable report in under 60 seconds</p>
            </div>
          </div>
        </section>

        {/* Validation checklist */}
        <section className="mb-12">
          <h2 className="mb-4 font-display text-2xl font-semibold text-white">
            Validation checklist (8/9)
          </h2>
          <div className="grid gap-2 sm:grid-cols-2">
            {checklist.map((item) => (
              <div
                key={item.label}
                className={`flex items-center gap-3 rounded-lg border px-4 py-3 ${
                  item.passed
                    ? "border-brand-700/40 bg-brand-900/20"
                    : "border-slate-700 bg-surface-800"
                }`}
              >
                <span
                  className={`text-lg ${
                    item.passed ? "text-brand-400" : "text-slate-600"
                  }`}
                >
                  {item.passed ? "✓" : "○"}
                </span>
                <span
                  className={`text-sm ${
                    item.passed ? "text-slate-300" : "text-slate-500"
                  }`}
                >
                  {item.label}
                </span>
              </div>
            ))}
          </div>
        </section>

        {/* Pain points */}
        <section className="mb-12">
          <h2 className="mb-4 font-display text-2xl font-semibold text-white">
            Source pain points (real posts)
          </h2>
          <div className="space-y-6">
            {painPoints.map((pp) => (
              <div key={pp.source} className="glass-card p-6">
                <p className="text-sm leading-relaxed text-slate-300">{pp.problem}</p>
                <div className="mt-4 grid gap-3 sm:grid-cols-2">
                  <div>
                    <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Persona</p>
                    <p className="text-sm text-slate-400">{pp.persona}</p>
                  </div>
                  <div>
                    <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Workaround</p>
                    <p className="text-sm text-slate-400">{pp.workaround}</p>
                  </div>
                  <div>
                    <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Frequency</p>
                    <p className="text-sm text-slate-400">{pp.frequency}</p>
                  </div>
                  <div>
                    <p className="text-xs font-bold uppercase tracking-wider text-slate-500">WTP signal</p>
                    <p className="text-sm text-slate-400">{pp.wtp}</p>
                  </div>
                </div>
                <a
                  href={pp.source}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="mt-4 inline-block text-sm text-brand-400 hover:text-brand-300"
                >
                  View source post →
                </a>
              </div>
            ))}
          </div>
        </section>

        <p className="text-center text-xs text-slate-600">
          Generated by Idea Miner run 2026-07-10-pm on 2026-07-10 20:41 UTC
        </p>

        <div className="mt-12 flex justify-center gap-4">
          <Link href="/demo" className="btn-primary">
            Try the Demo
          </Link>
          <Link href="/developers" className="btn-secondary">
            Developer Docs
          </Link>
        </div>
      </div>
    </>
  );
}
